name: Test and build

permissions:
  contents: read
  packages: write
  pull-requests: read

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  test:
    uses: ./.github/workflows/build-and-test.yml
  deploy_docker:
    needs: [test]
    uses: ./.github/workflows/docker-publish.yml
    permissions:
      contents: read
      packages: write
      pull-requests: read
  deploy_to_vps:
    needs: [deploy_docker]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy.yml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      APP_PATH: ${{ secrets.APP_PATH }}
